### ISSUE TITLE
Consideration of transitive dependencies

### ISSUE THREAD

**Issue by dovogt** [xvik/gradle-pom-plugin#2]
Is it possible with the plugin that the transitive flag from the configuration or at the dependency definition is respected? We have a flat dependency structure and manage the dependencies and version of the dependency ourselves. If I specify transitive in the configuration e.g., this is not considered during the pom generation.

`
configurations.all {
    transitive = false
}
or

api ("org.apache.xmlgraphics:xmlgraphics-commons:2.3") {transitive=false}
`

**Comment by xvik** [comment]
For direct transitive exclusion: 

```groovy
api ("org.apache.xmlgraphics:xmlgraphics-commons:2.3") {transitive=false}
```

I see the correct exclusion in pom

```xml
 <dependency>
      <groupId>org.apache.xmlgraphics</groupId>
      <artifactId>xmlgraphics-commons</artifactId>
      <version>2.3</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <artifactId>*</artifactId>
          <groupId>*</groupId>
        </exclusion>
      </exclusions>
    </dependency>
```
This is valid maven exclusion syntax since maven 3.2.1

If you have different behavior, please show me how to reproduce it.

`configurations.all {transitive = false}` case is not supported by maven-publish plugin. I don't want to support such case directly too because it will not work with BOM's in any case (cause more confusion). 
What you want to do is very easy to do using [manual xml modifications](https://github.com/xvik/gradle-pom-plugin#manual-pom-modification) like:
```groovy
withPomXml { Node node ->
    node.dependencies.dependency.each {
        it.children().last() + {
            exclusions {
                exclusion {
                    artifactId '*'
                    groupId '*'
                }
            }
        }
    }
}
```

**Comment by dovogt** [comment]
Thank you very much, sir. That helped me a lot. I use the way over the withPomXml()
